services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always



# docker run -it \
#  -e POSTGRES_USER="root" \
#  -e POSTGRES_PASSWORD="root" \
#  -e POSTGRES_DB="ny_taxi" \
#  -v c:/Users/BLESSING/Desktop/Data_Engineering/Data-Engineering/ny_taxi_data:/var/lib/postgresql/data \ 
#  -p 5432:5432 \
#  postgres:13
# docker run -d -e POSTGRES_USER="root" -e POSTGRES_PASSWORD="root" -e POSTGRES_DB="ny_taxi" -v c:/Users/BLESSING/Desktop/Data_Engineering/Data-Engineering/ny_taxi_data:/var/lib/postgresql/data -p 5432:5432 postgres:13

# ny_taxi_data
# C:\Users\BLESSING\Desktop\Data_Engineering\Data-Engineering\ny_taxi_data

# https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page